export interface IContact {
  _id: string;
  name: string,
  address : string,
  linkMap : string,
  description : string,
  phone1: string,
  phone2: string,
  email: string,
  phone3  : string,
  address2 : string,
  email2: string,
  address3 : string,
  email3 : string,
  facebook: string,
  zalo : string,
  youtube : string,
  whatapp : string,
  viber : string,
  ggAnalytic : string,
  ggSearch : string,
  linkMap2 : String,
  linkMap3 : String,
}

export interface IContactInputDTO {
  _id : string;
  name: string,
  address : string,
  linkMap : string,
  description : string,
  phone1: string,
  phone2: string,
  email: string,
  phone3 : string, 
  address2 : string,
  email2: string,
  address3 : string,
  email3 : string,
  facebook: string,
  zalo : string,
  youtube : string,
  whatapp : string,
  viber : string,
  ggAnalytic : string,
  ggSearch : string,
  linkMap2 : String,
  linkMap3 : String,
}
